## Some code about **Pytorch** (torch)

In [ ]:
!pip install torch

In [3]:
import torch

In [17]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [18]:
# The size of tensor x:
x.numel()

12

In [19]:
# The shape of tensor x:
x.shape

torch.Size([12])

In [31]:
# Reshape the tensor x:
y = x.reshape(3, 4)
print(y)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


In [21]:
# The shape of tensor y:
y.shape

torch.Size([3, 4])

In [34]:
# Also we can use -1 in case we don't know the size of the tensor:
z = x.reshape(4,-1)
print(z)
# Also
z = x.reshape(-1, 4)
print(z)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [39]:
# Tensor of zeros:
zeros = torch.zeros((2,3,4))
print(zeros)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [42]:
# Tensor of ones:
ones = torch.ones((2,3,4))
print(ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [46]:
# Tensor of random values (random sample):
s = torch.randn(3, 4)
print(s)

tensor([[ 0.1491,  0.9732,  0.1797,  0.3199],
        [-0.7769, -1.6565,  0.9043, -0.8225],
        [-0.8728, -0.2995,  0.5357,  0.1479]])


In [79]:
# Create a tensor of a specific values (list of values):

l = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
t = torch.tensor(l)
print(t)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


### Indexing and slicing

In [61]:
# Get the second tensor:
t[1]

tensor([5, 6, 7, 8])

In [62]:
# Get from second to the end tensors:
t[1:3]

tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [65]:
# Get the last tensor:
t[2]
# Or
t[-1]

tensor([ 9, 10, 11, 12])

In [68]:
# Get a specific element from a specific tensor:
t[2,0]

tensor(9)

In [80]:
# Change value of a specifc element:
t[2,0] = 20
t

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [20, 10, 11, 12]])

In [92]:
# Also we can change multiple elements:
t[:2, :] = 30
t

tensor([[30, 30, 30, 30],
        [30, 30, 30, 30],
        [20, 10, 11, 12]])

### Operations on Tensors

In [97]:
# Unary operations, for example exponential:
e = torch.exp(x)
e

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [104]:
# Binary operations, for example +,-,*,/,**:
u = torch.randn((3,3))
v = torch.randn((3,3))

c1 = u + v
c2 = u - v
c3 = u * v
c4 = u / v
c5 = u ** v

print(c1)
print(c2)
print(c3)
print(c4)
print(c5)

tensor([[-1.5310,  0.2290, -1.6929],
        [-1.4841, -0.8558, -0.0828],
        [-1.7330, -1.4374,  1.2990]])
tensor([[-1.2394, -2.5238,  0.7673],
        [-0.1794, -1.5359, -0.3338],
        [-1.8191,  2.4738,  0.6468]])
tensor([[ 0.2020, -1.5793,  0.5692],
        [ 0.5426, -0.4066, -0.0261],
        [-0.0765, -1.0133,  0.3173]])
tensor([[  9.4994,  -0.8336,   0.3762],
        [  1.2750,  -3.5165,  -1.6595],
        [-41.2573,  -0.2650,   2.9833]])
tensor([[   nan,    nan,    nan],
        [   nan,    nan,    nan],
        [   nan, 3.6171, 0.9911]])


In [115]:
# Concatenate multiple tensors:
l1 = [[0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10, 11]]

l2 = [[2.0, 1, 4, 3],
     [1, 2, 3, 4],
     [4, 3, 2, 1]]

x = torch.tensor(l1)
y = torch.tensor(l2)

torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [117]:
# Logical operation:
print(x == y)
print(x > y)
print(x < y)
print(x != y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[ True, False,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [125]:
# Get the sum of the tensor elements:
x.sum()

tensor(66)

### Broadcasting

In [203]:
a = torch.arange(3).reshape((3, 1,))
b = torch.arange(2).reshape((1, 2))
print("a: ", a)
print("b: ", b)

a:  tensor([[0],
        [1],
        [2]])
b:  tensor([[0, 1]])


In [204]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([[ 0, -1],
        [ 1,  0],
        [ 2,  1]])
tensor([[0, 0],
        [0, 1],
        [0, 2]])
tensor([[nan, 0.],
        [inf, 1.],
        [inf, 2.]])
tensor([[1, 0],
        [1, 1],
        [1, 2]])


### Saving the memory (allocate & derefrences)

In [176]:
# See how the address of the variable change when we change it value, and this is not good for the memory:
before = id(a)
a = a + b
print(id(a) == before)

False


In [178]:
# See how to change the value without changing the address by using [:] :
c = torch.zeros_like(a)
print("id(Z):", id(c))
c[:] = a + b
print("id(Z):", id(c))

id(Z): 139415731234960
id(Z): 139415731234960


In [177]:
# Or by using +=, *=, ...etc. :
before = id(a)
a += b
print(id(a) == before)

True


### Conversion to Other Python Objects

In [187]:
# Convert tensor to numpy array and vice versa:
x = torch.arange(10)

to_numpy = x.numpy()
from_numpy = torch.from_numpy(to_numpy)

print(type(to_numpy),type(from_numpy))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [194]:
# Convert tensor with a single scalar (one element in the tensor to a scalar):
a = torch.tensor([3.5])

# The tensor with a single element:
print(a)
# by using item() method:
print(a.item())
# or by built-in casting to float:
print(float(a))
# or by built-in casting to int:
print(int(a))

tensor([3.5000])
3.5
3.5
3
